{
  "hash": "63b0255112b2567524697e4618c80403",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Ex 01\"\nauthor: \"Liang Xiuhao Rydia\"\ndate: \"April 15, 2024\"\ndate-modified: \"last-modified\"\nexecute:\n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n\n# **Building Elegant and yet Informative Data Visualisation**\n\nFor the identification of sub-market, you can navigate straight to [**2.3.3 Identifying the sub-market**](https://va24-ry.netlify.app/take-home%20exercise/take-home_ex01/take-home_ex01#identifying-the-sub-markets)\n\nFor the final product, you can navigate straight to [**3.0 Data Visualisation**](https://va24-ry.netlify.app/take-home%20exercise/take-home_ex01/take-home_ex01#data-visualisation).\n\nIf not, you can proceed to enjoy reading the step by step thought process for this visualisation.\n\n## 1.0 Overview\n\n### 1.1 Setting the scene\n\nThere are two major residential property market in Singapore, namely public and private housing. Public housing aims to meet the basic need of the general public with monthly household income less than or equal to S\\$14,000. For families with monthly household income more than S\\$14,000, they need to turn to the private residential market.\n\n### 1.2 The Task\n\nAssuming the role of a graphical editor of a media company, you are requested to prepare minimum two and maximum three data visualisation to reveal the ***private residential market*** and **sub-markets of Singapore** for the 1st quarter of 2024.\n\n## 2.0 Set Up\n\n### 2.1 Loading the packages into R\n\nT he `pac::p_load()` function to load the required R packages in the working environment. The following packages are used in this set up:\n\n-   ggthemes: Extra themes, geoms, and scales for ggplot2.\n-   tidyverse: A collection of core packages designed for data science, used extensively for data preparation and wrangling.\n-   ggridges: a ggplot2 extension specially designed for plotting ridgeline plots\n-   colorspace:\n-   ggiraph: for making ‘ggplot’ graphics interactive.\n-   plotly: R library for plotting interactive statistical graphs.\n-   patchwork: specially designed for combining separate ggplot2 graphs into a single figure.\n-   lubridate: for easy and fast parsing of Date / Time\n-   ggrepel: an R package provides geoms for ggplot2 to repel overlapping text labels.\n-   ggdist: a ggplot2 extension specially design for visualising distribution and uncertainty\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load tidyverse from pacman\npacman::p_load(tidyverse,dplyr,ggridges,\n               ggthemes,colorspace,ggiraph,\n               plotly,patchwork,lubridate, \n               ggrepel,ggdist)\n```\n:::\n\n\n### 2.2 Importing the data sets\n\nFive sets of data are provided for this exercise:\n\n1.  2023 Quarter 1 Residential Transaction: ResidentialTransaction20240308160536.csv\n2.  2023 Quarter 2 Residential Transaction: ResidentialTransaction20240308160736.csv\n3.  2023 Quarter 3 Residential Transaction: ResidentialTransaction20240308161009.csv\n4.  2023 Quarter 4 Residential Transaction: ResidentialTransaction20240308161109.csv\n5.  2024 Quarter 1 Residential Transaction: ResidentialTransaction20240414220633.csv\n\nAll five sets of data consists of past transactions between Q1 of 2023 to Q1 of 2024, with 21 variables that will be explored in detail after the data sets are imported.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load transaction data using readr, part of tidyverse package\ndata.23Q1 <- read_csv(\"data/ResidentialTransaction20240308160536.csv\")\ndata.23Q2 <- read_csv(\"data/ResidentialTransaction20240308160736.csv\")\ndata.23Q3 <- read_csv(\"data/ResidentialTransaction20240308161009.csv\")\ndata.23Q4 <- read_csv(\"data/ResidentialTransaction20240308161109.csv\")\ndata.24Q1 <- read_csv(\"data/ResidentialTransaction20240414220633.csv\")\n```\n:::\n\n\nTo add new column `Quarter` into each of the csv file.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.23Q1$Quarter <- rep('23Q1',nrow(data.23Q1))\ndata.23Q2$Quarter <- rep('23Q2',nrow(data.23Q2))\ndata.23Q3$Quarter <- rep('23Q3',nrow(data.23Q3))\ndata.23Q4$Quarter <- rep('23Q4',nrow(data.23Q4))\ndata.24Q1$Quarter <- rep('24Q1',nrow(data.24Q1))\n```\n:::\n\n\nCombining all the data set into one\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- rbind(data.23Q1,data.23Q2,data.23Q3,data.23Q4,data.24Q1)\n```\n:::\n\n\nTo have a basic understanding of all 22 variables, `glimpse()` is used with 2024 Q1 data. We can see that there are 21 columns, with the following data types:\n\n-   doubles: `Transacted Price ($)`, `Area (SQFT)`, `Unit Price ($ PSF)`, `Area (SQM)`, `Unit Price ($ PSM)`, `Number of Units`\n\n-   characters: the rest of the 16 variables, including `Quarter`\n\nInterestingly, `Nett Price` is classified as characters, as it contains `-` character, although the rest of the columns should return doubles like `Transacted Price ($)`\n\n::: panel-tabset\n## The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# have a basic understanding for all 22 variables\nglimpse(df)\n```\n:::\n\n\n## The Output\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 26,806\nColumns: 22\n$ `Project Name`                <chr> \"THE REEF AT KING'S DOCK\", \"URBAN TREASU…\n$ `Transacted Price ($)`        <dbl> 2317000, 1823500, 1421112, 1258112, 1280…\n$ `Area (SQFT)`                 <dbl> 882.65, 882.65, 1076.40, 1033.34, 871.88…\n$ `Unit Price ($ PSF)`          <dbl> 2625, 2066, 1320, 1218, 1468, 1767, 1095…\n$ `Sale Date`                   <chr> \"01 Jan 2023\", \"02 Jan 2023\", \"02 Jan 20…\n$ Address                       <chr> \"12 HARBOURFRONT AVENUE #05-32\", \"205 JA…\n$ `Type of Sale`                <chr> \"New Sale\", \"New Sale\", \"New Sale\", \"New…\n$ `Type of Area`                <chr> \"Strata\", \"Strata\", \"Strata\", \"Strata\", …\n$ `Area (SQM)`                  <dbl> 82.0, 82.0, 100.0, 96.0, 81.0, 308.7, 42…\n$ `Unit Price ($ PSM)`          <dbl> 28256, 22238, 14211, 13105, 15802, 19015…\n$ `Nett Price($)`               <chr> \"-\", \"-\", \"-\", \"-\", \"-\", \"-\", \"-\", \"-\", …\n$ `Property Type`               <chr> \"Condominium\", \"Condominium\", \"Executive…\n$ `Number of Units`             <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ Tenure                        <chr> \"99 yrs from 12/01/2021\", \"Freehold\", \"9…\n$ `Completion Date`             <chr> \"Uncompleted\", \"Uncompleted\", \"Uncomplet…\n$ `Purchaser Address Indicator` <chr> \"HDB\", \"Private\", \"HDB\", \"HDB\", \"HDB\", \"…\n$ `Postal Code`                 <chr> \"097996\", \"419535\", \"269343\", \"269294\", …\n$ `Postal District`             <chr> \"04\", \"14\", \"27\", \"27\", \"28\", \"19\", \"10\"…\n$ `Postal Sector`               <chr> \"09\", \"41\", \"26\", \"26\", \"79\", \"54\", \"27\"…\n$ `Planning Region`             <chr> \"Central Region\", \"East Region\", \"North …\n$ `Planning Area`               <chr> \"Bukit Merah\", \"Bedok\", \"Yishun\", \"Yishu…\n$ Quarter                       <chr> \"23Q1\", \"23Q1\", \"23Q1\", \"23Q1\", \"23Q1\", …\n```\n\n\n:::\n:::\n\n:::\n\n### 2.3 Understanding the data\n\nOn top of the data types that is automatically assigned by R to help the program know how to process it, we can split the data into 4 types of data category to help ourselves for future analytics application. You can refer to the FAQ, Data Dictionary and Methodology in [URA website](https://www.ura.gov.sg/reis/dataDictionary).\n\n| Variable                      | Type                               | Appropriate Scale | Remarks                                                      |\n|------------------|------------------|------------------|------------------|\n| `Project Name`                | Qualitative / Nominal              | Discrete          |                                                              |\n| `Transacted Price ($)`        | Quantitative/ Numerical Continuous | Continuous        |                                                              |\n| `Area (SQFT)`                 | Quantitative/ Numerical Continuous | Continuous        |                                                              |\n| `Unit Price ($ PSF)`          | Quantitative/ Numerical Continuous | Continuous        |                                                              |\n| `Sales Date`                  | Date / Ordinal                     | Discrete          |                                                              |\n| `Address`                     | Qualitative / Nominal              | Discrete          |                                                              |\n| `Type of Sale`                | Qualitative / Nominal              | Discrete          |                                                              |\n| `Type of Area`                | Qualitative / Nominal              | Discrete          |                                                              |\n| `Area (SQM)`                  | Quantitative/ Numerical Continuous | Continuous        |                                                              |\n| `Unit Price ($ PSF)`          | Quantitative/ Numerical Continuous | Continuous        |                                                              |\n| `Nett Price($)`               | Quantitative/ Numerical Continuous | Continuous        |                                                              |\n| `Property Type`               | Qualitative/ Nominal               | Discrete          |                                                              |\n| `Number of Units`             | Quantitative/ Numerical Discrete   | Discrete          |                                                              |\n| `Tenure`                      | Nominal + Date / Ordinal           | None + Discrete   | Mixture of remaining lease date and tenure type and duration |\n| `Completion Date`             | Nominal + Date / Ordinal           | None + Discrete   | Mixture of \"Uncomplete\" status and completion date.          |\n| `Purchaser Address Indicator` | Qualitative / Nominal              | Discrete          |                                                              |\n| `Postal Code`                 | Qualitative / Nominal              | Discrete          |                                                              |\n| `Postal District`             | Qualitative / Nominal              | Discrete          |                                                              |\n| `Postal Sector`               | Qualitative / Nominal              | Discrete          |                                                              |\n| `Planning Region`             | Qualitative / Nominal              | Discrete          |                                                              |\n| `Planning Area`               | Qualitative / Nominal              | Discrete          |                                                              |\n| `Quarter`                     | Date / Ordinal                     | Discrete          | Created for ease of data analysis                            |\n\n[**Notes**]{.underline}\n\n1.  Contextually, some of the variables could be classified under ordinal. For example, I can choose to fill in the order for `Purchaser Address Indicator` as `Private` category is higher order than `HDB` category. The context is purchaser that address is `Private` is likely to be a person with higher Social Economic Status (SES) compared to a purchaser with `HDB` as address. Same could be applied to `Postal Code`, `Postal District`, `Postal Sector`, `Planning Region` and `Planning Area`.\n2.  Special Case: `Tenure` is still a character data type as of now. If we choose to use this column for analysis, we do need to do data preparation on this. `Tenure` date could also be classified under continuous data for more granularity. This variable will be a mixture of nominal data type with categories like \"Freehold\", and also quantitative data type using its `Tenure` date.\n3.  `Nett Price($)` is still a character data type as of now. If we choose to use this column for analysis, we do need to do data preparation on this.\n4.  Special Case: `Completion Date` is classified as character, but a quick look at the data `df`, we will realise that this variable is a mix of quantitative and qualitative data type of `Uncomplete` and actual date of completion, which could be converted and analyse as doubles.\n\n[**For simplicity of data analysis**]{.underline}\n\n1\\. `Transacted Price ($)` and `Nett Price($)` are similar. In this analysis, we will use `Transacted Price ($)` for simplicity, as `Nett Price($)` has fair amount of missing data, and it is prices after deducting the value of the indirect discounts or benefits, and not representative for all transactions.\n\n2.  `Area (SQFT)` and `Area (SQM)`, and `Unit Price ($ PSF)` and `Unit Price ($ PSM)` are similar measures in different unit. We will use `Area (SQFT)` and `Unit Price ($ PSF)`\n\nNext we look at the basic statistics of the current data using `summary()`\n\n::: panel-tabset\n### The Output\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n Project Name       Transacted Price ($)  Area (SQFT)       Unit Price ($ PSF)\n Length:26806       Min.   :   440000    Min.   :   322.9   Min.   : 138      \n Class :character   1st Qu.:  1280000    1st Qu.:   721.2   1st Qu.:1384      \n Mode  :character   Median :  1660000    Median :   990.3   Median :1762      \n                    Mean   :  2143286    Mean   :  1191.6   Mean   :1852      \n                    3rd Qu.:  2320000    3rd Qu.:  1302.4   3rd Qu.:2260      \n                    Max.   :392180000    Max.   :144883.4   Max.   :5756      \n                                                                              \n  Sale Date           Address          Type of Sale       Type of Area      \n Length:26806       Length:26806       Length:26806       Length:26806      \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   Area (SQM)      Unit Price ($ PSM) Nett Price($)      Property Type     \n Min.   :   30.0   Min.   : 1484      Length:26806       Length:26806      \n 1st Qu.:   67.0   1st Qu.:14893      Class :character   Class :character  \n Median :   92.0   Median :18966      Mode  :character   Mode  :character  \n Mean   :  110.5   Mean   :19930                                           \n 3rd Qu.:  121.0   3rd Qu.:24327                                           \n Max.   :13460.0   Max.   :61962                                           \n NA's   :6                                                                 \n Number of Units     Tenure          Completion Date   \n Min.   : 1.000   Length:26806       Length:26806      \n 1st Qu.: 1.000   Class :character   Class :character  \n Median : 1.000   Mode  :character   Mode  :character  \n Mean   : 1.005                                        \n 3rd Qu.: 1.000                                        \n Max.   :60.000                                        \n                                                       \n Purchaser Address Indicator Postal Code        Postal District   \n Length:26806                Length:26806       Length:26806      \n Class :character            Class :character   Class :character  \n Mode  :character            Mode  :character   Mode  :character  \n                                                                  \n                                                                  \n                                                                  \n                                                                  \n Postal Sector      Planning Region    Planning Area        Quarter         \n Length:26806       Length:26806       Length:26806       Length:26806      \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n```\n\n\n:::\n:::\n\n\n### The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# data summary\nsummary(df)\n```\n:::\n\n:::\n\nFrom the continuous data above, we can conclude that there is a possibility of extreme outliers. The `Number of Units` has a max of 60, while the 3rd Quartile is 1.000. Let's examine the data by sorting it in descending order using `arrange(desc())` and take a look at data with `Number of Units`, as it greatly affect the analysis of `Transaction Price ($)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>%\n  filter(`Number of Units` > 1) %>%\n  arrange(desc(`Number of Units`)) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 22\n   `Project Name`      `Transacted Price ($)` `Area (SQFT)` `Unit Price ($ PSF)`\n   <chr>                                <dbl>         <dbl>                <dbl>\n 1 MEYER PARK                       392180000       144883.                 2707\n 2 BAGNALL COURT                    115280000        68491.                 1683\n 3 KEW LODGE                         66800000        25177                  2653\n 4 KARTAR APARTMENTS                 18000000         6964.                 2585\n 5 MONDO MANSION BUIL…                6280000         5490.                 1144\n 6 N.A.                              10600000         6747.                 1571\n 7 N.A.                              61080008        32149.                 1900\n 8 N.A.                              32200000        14123.                 2280\n 9 N.A.                               6150000         4342.                 1416\n10 EAST VIEW GARDEN                   6100000         8338.                  732\n11 N.A.                               8000000         3659.                 2187\n12 CLAYMORE PLAZA                     7000000         4209.                 1663\n# ℹ 18 more variables: `Sale Date` <chr>, Address <chr>, `Type of Sale` <chr>,\n#   `Type of Area` <chr>, `Area (SQM)` <dbl>, `Unit Price ($ PSM)` <dbl>,\n#   `Nett Price($)` <chr>, `Property Type` <chr>, `Number of Units` <dbl>,\n#   Tenure <chr>, `Completion Date` <chr>, `Purchaser Address Indicator` <chr>,\n#   `Postal Code` <chr>, `Postal District` <chr>, `Postal Sector` <chr>,\n#   `Planning Region` <chr>, `Planning Area` <chr>, Quarter <chr>\n```\n\n\n:::\n:::\n\n\nWe have 12 rows that have transactions containing more than 1 unit sold, and a check on the `Address` shows that there are 5 sales that are en bloc cases which should be remove from the analysis. These en bloc cases are likely sales to companies for purpose of redevelopment rather than individual purchasers. See this [link](https://www.businesstimes.com.sg/companies-markets/meyer-park-sold-uol-singapore-land-group-jv-s39218-million-third-en-bloc-attempt) on the Meyer Park en bloc transaction. Otherwise, those 7 cases of transactions with more than one unit sold should be included as are likely the cases of purchase of multiple units or the purchase of multiple adjacent plots of land.\n\n### 2.3.1 Removing the en bloc sales (irrelevant data)\n\nFor the follow code chunk, we aim to remove all the enbloc sales, including the 5 transactions that we have found in section 2.3. While we have no idea if there are more than 5 cases of en bloc sales, the follow code chunk will effectively remove all the rows with the string \"ENBLOC\" in `Address` column.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.c <- df %>%\n  filter(!grepl('ENBLOC', df$Address))\ndf.c\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 26,801 × 22\n   `Project Name`      `Transacted Price ($)` `Area (SQFT)` `Unit Price ($ PSF)`\n   <chr>                                <dbl>         <dbl>                <dbl>\n 1 THE REEF AT KING'S…                2317000          883.                 2625\n 2 URBAN TREASURES                    1823500          883.                 2066\n 3 NORTH GAIA                         1421112         1076.                 1320\n 4 NORTH GAIA                         1258112         1033.                 1218\n 5 PARC BOTANNIA                      1280000          872.                 1468\n 6 NANYANG PARK                       5870000         3323.                 1767\n 7 PALMS @ SIXTH AVEN…                4950000         4521.                 1095\n 8 N.A.                               3260000         1555.                 2096\n 9 WHISTLER GRAND                      850000          441.                 1926\n10 NORTHOAKS                          1268000         1604.                  791\n# ℹ 26,791 more rows\n# ℹ 18 more variables: `Sale Date` <chr>, Address <chr>, `Type of Sale` <chr>,\n#   `Type of Area` <chr>, `Area (SQM)` <dbl>, `Unit Price ($ PSM)` <dbl>,\n#   `Nett Price($)` <chr>, `Property Type` <chr>, `Number of Units` <dbl>,\n#   Tenure <chr>, `Completion Date` <chr>, `Purchaser Address Indicator` <chr>,\n#   `Postal Code` <chr>, `Postal District` <chr>, `Postal Sector` <chr>,\n#   `Planning Region` <chr>, `Planning Area` <chr>, Quarter <chr>\n```\n\n\n:::\n:::\n\n\nIn the df.c tibble, it showed that 5 rows had been removed. Now there is only 26,801 rows instead of the original 26,806 rows in the initial df. This confirm that there are only 5 en bloc sales in the data frame.\n\n### 2.3.2 Treatment for multiple units Transactions\n\nAfter removing the 5 en bloc sales, we are still left with 7 transactions that has between 2 to 4 units sold per transaction. This has caused the `Transacted Price ($)` to be greatly inflated. In dealing with this, we can (1) choose to divide the `Transacted Price ($)` by the number of units sold, or (2) remove them from the analysis. In this analysis, we will be using method (2), to remove these transactions from the data set for further analysis. The reason to do so is that we cannot determine at this stage that each unit in the sales are equally priced, or whether each unit has the same `Area` size.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.c <- df.c %>%\n  filter(`Number of Units` <= 1)\n```\n:::\n\n\n### 2.3.3 Identifying the sub-markets\n\n**Land vs. Strata**\n\nTo lend some background context, you can refer to this link: [Landed vs. Strata Landed](https://plbinsights.com/landed-vs-strata-landed-whats-the-difference-how-have-they-performed-in-recent-years/#:~:text=According%20to%20the%20URA%20website,as%20a%20pure%20landed%20property.) Basically, `Strata` means you only owns the property build on this land, but do not own the land itself. `Land` means you own the land and have more freedom and responsibility in terms of the constructions etc. The application of this knowledge for analysis is that `Strata` and `Land` classification can be identify as the sub-markets as owning a piece of land is likely to be more expensive for the purchaser compared to `Strata` title.\n\nThe plot below shows the 10 sub-markets in Singapore private housing market.\n\n**Land**\n\n1.  Apartment\n2.  Detached House\n3.  Semi-Detached House\n4.  Terrace House\n\n**Strata**\n\n1.  Apartment\n2.  Condominium\n3.  Detached House\n4.  Executive Condominium\n5.  Semi-Detached House\n6.  Terrace House\n\n::: panel-tabset\n## The Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n## The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>%\n  select(`Transacted Price ($)`, `Type of Area`, `Property Type`) %>%\n  group_by(`Property Type`, `Type of Area`) %>%\n  summarise(`Median Transaction Price ($)` = median(`Transacted Price ($)`, .groups = 'drop')) %>%\n  ggplot(aes(x = `Property Type`, \n             y = `Median Transaction Price ($)`, \n             color = `Type of Area`)) +  # Adding color aesthetic based on Type of Area\n  geom_point() +\n  theme(axis.text.x = element_text(size = 8, angle = 90, vjust = 0.5, hjust=1)) +\n  scale_y_continuous(labels = scales::comma) +\n  labs(color = \"Type of Area\")\n```\n:::\n\n:::\n\n**Conclusion**\n\nFrom the Median Transacted Price plot above, we observe that the 10 sub-markets are distinct in pricing, with `Land` `Type of Area` generally priced a lot higher than `Strata`, especially in the `Apartment` and `Detached House` categories.\n\n## 3.0 Data Visualisation\n\n### 3.1.1 Selection of Sub-markets\n\nIn this section, we would want to focus on the Apartment(Strata) Condominium and Executive Condominium sub-market in Singapore, out of the 10 sub-markets identified in section 2.3.3. As stated in section [1.1 Setting the scene](https://va24-ry.netlify.app/take-home%20exercise/take-home_ex01/take-home_ex01#setting-the-scene), for families with monthly household income more than S\\$14,000, they need to turn to the private residential market. However, due limited number of plots to be shown, we will take Condominium as example for the illustrations\n\nAssumptions and considerations for the selecting the sub-markets to visualise:\n\n1.  **Affordability** - According to the this [article](https://www.propertyguru.com.sg/property-guides/the-different-types-of-housing-in-singapore-9916), apartment(Strata), Executive Condominium and Condominium are the next most affordable type of private housing if the family is not eligible to purchase public housing. This corroborate with the Median Transaction Price plot above.\n\n2.  **Target Audience** - The target audience for this graphics will be the public who would like to consider housing option in the private residential market. The target audience are those who's family household are above the limits and would like to look for relatively affordable housing option in the private residential market as mentioned above in point 1.\n\n3.  **Information Required** - Pricing, Location, Types of Sales, Unit Price, Size of Property\n\n## 3.2 The Plots\n\n### 3.2.1 The Pricing across Planning Regions\n\n**Plot 1: Pricing for non-freehold Condominium**\n\nThis first plot focus on Condominium that are not of Freehold Tenure. Compared to freehold property, these non-freehold Condominiums are relatively lower price. The plot below shows the distribution of `Transacted Price ($)` in the five `Planning Region` in Singapore, and reveal the median price of each region varies from 1 to 2 million, with North Region with a tighter spread at a lower price than the other four regions. The Central Region has the highest median at 2 million, with a widest spread. The 4th quantile of the Central Region consists of `Transacted Price ($)` between 2.5 to just after 9 million. This shows that the Condominiums with Lease are more affordable in the North and East Region in Singapore, with North East and West Region next, and finally the most expensive Condominium would be the ones found in Central Region.\n\n::: panel-tabset\n## The Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n## The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.c %>%\n  filter(`Type of Area` == 'Strata',`Property Type` == 'Condominium', `Quarter` == '24Q1', `Tenure`!= 'Freehold') %>%\n  ggplot(aes(x = `Transacted Price ($)`,\n           y = `Planning Region`,\n           fill = factor(stat(quantile))\n           )) +\n  stat_density_ridges(\n    geom = \"density_ridges_gradient\",\n    calc_ecdf = TRUE,\n    quantiles = 4,\n    quantile_lines = TRUE) +\n  scale_fill_viridis_d(name = \"Quartiles\",\n                       option = \"A\") +\n  scale_x_continuous(name = \"Transacted Price in million ($)\",\n    labels = c(0,1,2,3,4,5,6,7,8,9,10), \n    breaks = c(0,1000000,2000000,3000000,4000000,5000000,6000000,7000000,8000000,9000000,10000000)) +\n  theme_economist() + \n  ggtitle(\"24Q1 Non-Freehold Condo Transacted Price by Planning Region\") +\n  theme(plot.title = element_text(size=12))\n```\n:::\n\n:::\n\n### 3.2.2 The Median Unit Price (\\$ PSF) in Past 5 Quarters\n\n**Plot 2: Mean and Median Unit Price for non-freehold Condominium**\n\nPlot 2 focus on the mean and median `Unit Price ($ PSF)` for the non-freehold Condominium in the Central Region. The Mean `Unit Price ($ PSF)` is represented by the red dot in each of the violin plot and boxplot. While we see a slight rise in the mean and median `Unit Price ($ PSF)` in 23Q2, where there are more transactions with `Unit Price ($ PSF)` in the \\$2,500 range, represented by the bulge at the top of the violin plot. For the rest of the quarters, the mean and median `Unit Price ($ PSF)` hovers around the range of \\$2,000. Despite the mean and median are at \\$2,000 for the 24Q1, there is also a sizable transaction of `Unit Price ($ PSF)` of \\$3,000 happening in 24Q1, as represented by the slight bulge at the top of the violin plot.\n\n::: panel-tabset\n## The Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n## The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquarter_means <- df.c %>%\n  filter(`Property Type` == 'Condominium',`Planning Region` == \"Central Region\", `Tenure`!= 'Freehold') %>%\n  group_by(Quarter) %>%\n  summarise(mean_uprice = mean(`Unit Price ($ PSF)`))\n\ndf.c %>%\n  filter(`Property Type` == 'Condominium', `Planning Region` == \"Central Region\",`Tenure`!= 'Freehold') %>%\n  ggplot(aes(y=`Unit Price ($ PSF)`,\n           x=`Quarter`)\n       )+\n  geom_violin() +\n  geom_boxplot(width = .20,\n               outlier.shape = NA) +\n  geom_point(data = quarter_means, \n             aes(y = mean_uprice), \n             color = \"red\", \n             size = 3) +\n    scale_y_continuous(labels = scales::comma) +\n  theme_economist() +\n  ggtitle(\"Condominium Unit Price ($ PSF) for Central Region\") \n```\n:::\n\n:::\n\n### 3.2.3 Purchaser Address Indicator\n\n**Plot 3: Purchaser Address Indicator for non-freehold Condominium**\n\nPlot 3 focus on the top and bottom 5% of the different types of purchasers for non-freehold Condominium in the Central Region. We assume that the N.A type are purchasers who do not own any property in Singapore. The top 5% of the Private category purchase units priced at \\$4.5-\\$9 million. For HDB and N.A categories, the top 5% are purchasing units that is priced between \\$3 to 4 million. Both bottom 5% Private and HDB categories purchase unit of \\$1 million, while the bottom 5% N.A category are buying unit just above \\$1 million. The plausible reason is that purchaser in N.A. category may want to buy a unit for their own stay since they do not own any other properties. Hence, they are paying slightly more for a larger unit relative to other two types of purchasers, who might be buying studio units for rental income.\n\n::: panel-tabset\n## The Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n## The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.c %>%\n  filter(`Property Type` == 'Condominium', `Quarter` == '24Q1', `Planning Region` == \"Central Region\", `Tenure` != 'Freehold') %>%\n  ggplot(aes(x = `Transacted Price ($)`, \n           y = `Purchaser Address Indicator`, \n           fill = factor(stat(quantile))\n           )) +\n  stat_density_ridges(\n    geom = \"density_ridges_gradient\",\n    calc_ecdf = TRUE, \n    quantiles = c(0.05, 0.95)\n    ) +\n  scale_fill_manual(\n    name = \"Percentage of Total\",\n    values = c(\"#FF00FFA0\", \"#FFE4E1A0\", \"#0000ffA0\"),\n    labels = c(\"Bottom 5%\", \"5-95%\", \"Top 5%\")\n  ) +\n  theme_ridges()+\n  theme_economist() +\n  theme(plot.title = element_text(size=12)) +\n  scale_x_continuous(name = \"Transacted Price in million ($)\",\n    labels = c(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15), \n    breaks = c(0,1000000,2000000,3000000,4000000,5000000,6000000,7000000,8000000,9000000,10000000,11000000, 12000000, 13000000, 14000000, 15000000)) + \n  ggtitle(\"Central Region Condominium: Purchaser Address Indicator 24Q1\")\n```\n:::\n\n:::\n\n## 4.0 References\n\n1\\. T.S. Kam, R for Visual Analytics [Chapter 9](https://r4va.netlify.app/chap09) for visualisation of Ridgeline plots with quantile lines.\n\n2\\. Claus O. Wilke, Fundamentals of Data Visualization [Chapter 2](https://clauswilke.com/dataviz/aesthetic-mapping.html) for understanding and classification of variables.\n\n3\\. Stack Overflow, [\"Filter rows which contain a certain string\"](https://stackoverflow.com/questions/22850026/filter-rows-which-contain-a-certain-string) for removing en bloc sales from the data frame.\n",
    "supporting": [
      "Take-home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}