project:
  type: website

website:
  title: "Visual Analytics"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Learning Journey
        href: landing.qmd
      - text: Hands-on Exercise
        menu: 
          - text: "Hands-on Exercise 1"
            href: Hands-on Exercise/hands-on-ex1.qmd
      - text: In-class Exercise
        menu: 
          - text: "In-class Exercise 1"
            href: In-class Exercise/In-class_Ex01/In-class_Ex01.qmd
          - text: "In-class Exercise 2"
            href: XXXX

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

