project:
  type: website

website:
  title: "Visual_Analytics"
  navbar:
    left:
      - text: Hands-on Exercise
        menu: 
          - text: "In-class Exercise 1"
            href: "In-class Exercise/In-class_Ex01.qmd"
      - text: In-class Exercise
        menu: 
          - text: "In-class Exercise 1"
            href: "In-class_Exercise/In-class_Ex01"
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

