project:
  type: website

website:
  title: "VA 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Hands-on Exercise
        menu: 
          - text: "Hands-on Exercise"
            href: 
      - text: In-class Exercise
        menu: 
          - text: "In-class Exercise 1"
            href: In-class_Ex01.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

