---
title: "In-class_Ex02"
author: "Liang Xiuhao Rydia"
date: "20 April 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

```{r}
pacman::p_load(tidyverse,ggdist,ggthemes,colorspaces,ggridges)
```

```{r}
exam_df <- read_csv("data/Exam_data.csv")
```
## Histogram

::: panel-tabset
## The Plot
```{r}
#| echo: False
ggplot(exam_df,
       aes(x = ENGLISH)) +
  geom_histogram()
```
## The Code
```{r}
#| eval: False
ggplot(exam_df,
       aes(x = ENGLISH)) +
  geom_histogram()
```
:::


```{r}
#| echo: False
ggplot(exam_df,
       aes(x = ENGLISH)) +
  geom_density(
    color = "#1696d2",
    adjust = .65,
    alpha = .6
  )
```
:::

```{r}
#| eval: False
ggplot(exam_df,
       aes(x = ENGLISH)) +
  geom_density(
    color = "#1696d2",
    adjust = .65,
    alpha = .6
  )
```

## The alternative design

```{r}
median_eng <- median(exam_df$ENGLISH)
mean_eng <- mean(exam_df$ENGLISH)
std_eng <- sd(exam_df$ENGLISH)

ggplot(exam_df,
       aes(x= ENGLISH)) +
  geom_density(
    color = "#1696d2",
    adjust = .65,
    alpha = .6) +
  stat_function(
    fun = dnorm,
    args = list(mean = mean_eng,
                sd = std_eng),
    col = "grey30",
    linewidth = .8) +
  geom_vline(
    aes(xintercept = mean_eng),
    color = "#4d5887",
    linewidth = .6,
    linetype = "dashed") +
  annotate(geom = "text",
           x = mean_eng - 8,
           y = 0.04,
           label = paste0("Mean ENGLISH: ",
                          round((mean_eng), 2)),
           color = "#4d5887") +
  geom_vline(
    aes(xintercept = median_eng)
  )
  
```




